language: objective-c
osx_image: xcode8.3
xcode_workspace: SPS.xcworkspace
xcode_scheme: SPS

cache:
  bundler: true
  cocoapods: true

branches:
  only:
  - master #build on push only on master branch
  - develop

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec pod install --repo-update

script:
- set -o pipefail
- xcodebuild clean test -workspace SPS.xcworkspace -scheme SPS -destination "name=iPhone SE" | xcpretty -c

after_success:
- bash <(curl -s https://codecov.io/bash) -J 'SPS'

